In [32]:
import requests
import pandas as pd

def fetch_bea_data(api_key, dataset_name, table_id, frequency, year):

    base_url = "https://apps.bea.gov/api/data"
    params = {
        "UserID": api_key,
        "method": "GetData",
        "datasetname": dataset_name,
        "TableName": table_id,
        "Frequency": frequency,
        "Year": year,
        "ResultFormat": "JSON"
    }
    response = requests.get(base_url, params=params)
    if response.status_code == 200:
        data = response.json()
        # Navigate through the JSON structure to get to the actual data
        data_items = data['BEAAPI']['Results']['Data']
        # Create a DataFrame
        df = pd.DataFrame(data_items)
        return df
    else:
        print(f"Error fetching data: {response.status_code}")
        return None

api_key = "E8136D09-6A01-4F53-B11F-74762020B84A"
dataset_name = "NIPA"
table_id = "T20600"  
frequency = "M"  
year = "2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023"

data = fetch_bea_data(api_key, dataset_name, table_id, frequency, year)
data

,TableName,SeriesCode,LineNumber,LineDescription,TimePeriod,METRIC_NAME,CL_UNIT,UNIT_MULT,DataValue,NoteRef
0,T20600,A065RC,1,Personal income,2003M01,Current Dollars,Level,6,"9,290,106",T20600
1,T20600,A065RC,1,Personal income,2003M02,Current Dollars,Level,6,"9,296,201",T20600
2,T20600,A065RC,1,Personal income,2003M03,Current Dollars,Level,6,"9,333,827",T20600
3,T20600,A065RC,1,Personal income,2003M04,Current Dollars,Level,6,"9,356,358",T20600
4,T20600,A065RC,1,Personal income,2003M05,Current Dollars,Level,6,"9,414,424",T20600
...,...,...,...,...,...,...,...,...,...,...
10831,T20600,A067RM,43,"Disposable personal income, chained (2017) dol...",2023M08,Chained Dollars,Percent change,0,0.0,T20600
10832,T20600,A067RM,43,"Disposable personal income, chained (2017) dol...",2023M09,Chained Dollars,Percent change,0,-0.1,T20600
10833,T20600,A067RM,43,"Disposable personal income, chained (2017) dol...",2023M10,Chained Dollars,Percent change,0,0.3,T20600
10834,T20600,A067RM,43,"Disposable personal income, chained (2017) dol...",2023M11,Chained Dollars,Percent change,0,0.5,T20600
10835,T20600,A067RM,43,"Disposable personal income, chained (2017) dol...",2023M12,Chained Dollars,Percent change,0,0.1,T20600

In [28]:
data[data['TimePeriod'] == '2020M01']

,TableName,SeriesCode,LineNumber,LineDescription,TimePeriod,METRIC_NAME,CL_UNIT,UNIT_MULT,DataValue,NoteRef
0,T20600,A065RC,1,Personal income,2020M01,Current Dollars,Level,6,"18,821,549",T20600
12,T20600,A033RC,2,Compensation of employees,2020M01,Current Dollars,Level,6,"11,804,695",T20600
24,T20600,A034RC,3,Wages and salaries,2020M01,Current Dollars,Level,6,"9,646,468",T20600
36,T20600,A132RC,4,Private industries,2020M01,Current Dollars,Level,6,"8,143,449",T20600
48,T20600,B202RC,5,Government,2020M01,Current Dollars,Level,6,"1,503,019",T20600
60,T20600,A038RC,6,Supplements to wages and salaries,2020M01,Current Dollars,Level,6,"2,158,227",T20600
72,T20600,B040RC,7,Employer contributions for employee pension an...,2020M01,Current Dollars,Level,6,"1,490,801","T20600,T20600.1"
84,T20600,B039RC,8,Employer contributions for government social i...,2020M01,Current Dollars,Level,6,"667,425",T20600
96,T20600,A041RC,9,Proprietors' income with inventory valuation a...,2020M01,Current Dollars,Level,6,"1,626,016",T20600
108,T20600,B042RC,10,Farm,2020M01,Current Dollars,Level,6,"36,515",T20600
120,T20600,A045RC,11,Nonfarm,2020M01,Current Dollars,Level,6,"1,589,501",T20600
132,T20600,A048RC,12,Rental income of persons with capital consumpt...,2020M01,Current Dollars,Level,6,"733,900",T20600
144,T20600,W210RC,13,Personal income receipts on assets,2020M01,Current Dollars,Level,6,"2,938,438",T20600
156,T20600,A064RC,14,Personal interest income,2020M01,Current Dollars,Level,6,"1,562,981",T20600
168,T20600,B703RC,15,Personal dividend income,2020M01,Current Dollars,Level,6,"1,375,457",T20600
180,T20600,A577RC,16,Personal current transfer receipts,2020M01,Current Dollars,Level,6,"3,189,482",T20600
192,T20600,A063RC,17,Government social benefits to persons,2020M01,Current Dollars,Level,6,"3,144,224",T20600
204,T20600,W823RC,18,Social security,2020M01,Current Dollars,Level,6,"1,063,995","T20600,T20600.2"
216,T20600,W824RC,19,Medicare,2020M01,Current Dollars,Level,6,"798,095","T20600,T20600.3"
228,T20600,W729RC,20,Medicaid,2020M01,Current Dollars,Level,6,"603,397",T20600
240,T20600,W825RC,21,Unemployment insurance,2020M01,Current Dollars,Level,6,"27,886",T20600
252,T20600,W826RC,22,Veterans' benefits,2020M01,Current Dollars,Level,6,"139,692",T20600
264,T20600,W827RC,23,Other,2020M01,Current Dollars,Level,6,"511,160",T20600
276,T20600,B931RC,24,"Other current transfer receipts, from business...",2020M01,Current Dollars,Level,6,"45,257",T20600
288,T20600,A061RC,25,Less: Contributions for government social insu...,2020M01,Current Dollars,Level,6,"1,470,982",T20600
300,T20600,W055RC,26,Less: Personal current taxes,2020M01,Current Dollars,Level,6,"2,263,955",T20600
312,T20600,A067RC,27,Equals: Disposable personal income,2020M01,Current Dollars,Level,6,"16,557,594",T20600
324,T20600,A068RC,28,Less: Personal outlays,2020M01,Current Dollars,Level,6,"15,366,176",T20600
336,T20600,DPCERC,29,Personal consumption expenditures,2020M01,Current Dollars,Level,6,"14,815,670",T20600
348,T20600,B069RC,30,Personal interest payments,2020M01,Current Dollars,Level,6,"350,131","T20600,T20600.4"
360,T20600,W211RC,31,Personal current transfer payments,2020M01,Current Dollars,Level,6,"200,375",T20600
372,T20600,W062RC,32,To government,2020M01,Current Dollars,Level,6,"107,174",T20600
384,T20600,B070RC,33,To the rest of the world (net),2020M01,Current Dollars,Level,6,"93,201",T20600
396,T20600,A071RC,34,Equals: Personal saving,2020M01,Current Dollars,Level,6,"1,191,418",T20600
408,T20600,A072RC,35,Personal saving as a percentage of disposable ...,2020M01,Ratio,Level,0,7.2,T20600
420,T20600,W875RX,36,Personal income excluding current transfer rec...,2020M01,Chained Dollars,Level,6,"14,966,421","T20600,T20600.5"
432,T20600,A067RX,37,"Total, Billions of chained (2017) dollars",2020M01,Chained Dollars,Level,6,"15,852,537","T20600,T20600.5"
444,T20600,A229RC,38,Current dollars,2020M01,Ratio,Level,0,"49,956",T20600
456,T20600,A229RX,39,Chained (2017) dollars,2020M01,Ratio,Level,0,"47,829",T20600
468,T20600,B230RC,40,"Population (midperiod, thousands)",2020M01,Persons,Level,3,"331,443","T20600,T20600.6"
480,T20600,A067RCM,41,"Disposable personal income, current dollars",2020M01,Current Dollars,Percent change,0,1.2,T20600
492,T20600,PF000969,42,"Personal outlays, current dollars",2020M01,Current Dollars,Percent change,0,0.4,T20600
504,T20600,A067RM,43,"Disposable personal income, chained (2017) dol...",2020M01,Chained Dollars,Percent change,0,1.1,T20600

In [12]:
data['LineDescription'].value_counts()

Personal income                                                                            12
To the rest of the world (net)                                                             12
Less: Contributions for government social insurance, domestic                              12
Less: Personal current taxes                                                               12
Equals: Disposable personal income                                                         12
Less: Personal outlays                                                                     12
Personal consumption expenditures                                                          12
Personal interest payments                                                                 12
Personal current transfer payments                                                         12
To government                                                                              12
Equals: Personal saving                                                                    12
Other                                                                                      12
Personal saving as a percentage of disposable personal income                              12
Personal income excluding current transfer receipts, Billions of chained (2017) dollars    12
Total, Billions of chained (2017) dollars                                                  12
Current dollars                                                                            12
Chained (2017) dollars                                                                     12
Population (midperiod, thousands)                                                          12
Disposable personal income, current dollars                                                12
Personal outlays, current dollars                                                          12
Other current transfer receipts, from business (net)                                       12
Veterans' benefits                                                                         12
Compensation of employees                                                                  12
Nonfarm                                                                                    12
Wages and salaries                                                                         12
Private industries                                                                         12
Government                                                                                 12
Supplements to wages and salaries                                                          12
Employer contributions for employee pension and insurance funds                            12
Employer contributions for government social insurance                                     12
Proprietors' income with inventory valuation and capital consumption adjustments           12
Farm                                                                                       12
Rental income of persons with capital consumption adjustment                               12
Unemployment insurance                                                                     12
Personal income receipts on assets                                                         12
Personal interest income                                                                   12
Personal dividend income                                                                   12
Personal current transfer receipts                                                         12
Government social benefits to persons                                                      12
Social security                                                                            12
Medicare                                                                                   12
Medicaid                                                                                   12
Disposable personal income, chained (2017) dollars                                         12
Name: LineDescription, dtype: int64

In [25]:
data[data['TimePeriod'] == '2020M01']

Empty DataFrame
Columns: [TableName, SeriesCode, LineNumber, LineDescription, TimePeriod, METRIC_NAME, CL_UNIT, UNIT_MULT, DataValue, NoteRef]
Index: []